services:
  frontend:
    image: 426192960096.dkr.ecr.us-east-1.amazonaws.com/frontend-app:latest
    container_name: frontend-app
    ports:
      - "80:80"
    networks:
      - appnet
    depends_on:
      - backend

  backend:
    image: 426192960096.dkr.ecr.us-east-1.amazonaws.com/backend-app:latest
    container_name: backend-app
    ports:
      - "84:80"
    environment:
      DB_HOST: mysql-db
      DB_USERNAME: admin
      DB_PASSWORD: Devops123
      DB_PORT: 3306
    networks:
      - appnet
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: 426192960096.dkr.ecr.us-east-1.amazonaws.com/mysql-db:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Cloud122
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: Devops123
    ports:
      - "3306:3306"
    networks:
      - appnet
    volumes:
      - mysql_data:/var/lib/mysql
